[package]
name = "lines"
version = "0.1.0"
authors = ["erikrudie"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33.0"
# TODO update to 33
